[package]
name = "mania"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
mania-macros = { path = "../mania-macros" }
arc-swap = { version = "1.7.1", features = ["serde"] }
byteorder = "1.5.0"
bytes = { version = "1.9.0", features = ["serde"] }
chrono = { version = "0.4.39", features = ["serde"] }
dashmap = "6.1.0"
flate2 = "1.0.35"
generic-array = "1.2.0"
phf = { version = "0.11.3", features = ["macros"] }
prost = "0.13.4"
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
surge-ping = "0.8.1"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["net", "io-util", "time", "macros", "rt-multi-thread", "signal", "tracing"] }
tracing = "0.1.41"
uuid = { version = "1.12.0", features = ["serde", "v4"] }
hex = { workspace = true }
reqwest = "0.12.12"
serde_json = "1.0.135"
futures = "0.3.31"
inventory = "0.3.17"
once_cell = "1.20.2"
p256 = {version = "0.13.2", features = ["ecdh"]}
md-5 = { workspace = true }
elliptic-curve = "0.13.8"
log = "0.4.25"
rand_chacha = "0.3.1"
num_enum = "0.7.3"

[build-dependencies]
prost-build = "0.13.4"
glob = "0.3.2"