[package]
name = "mania-examples"
version.workspace = true
edition.workspace = true
license-file.workspace = true
description = "examples for mania"

[dependencies]
cfg-if.workspace = true
console-subscriber = { workspace = true, optional = true }
mania.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[features]
default = []
tokio-tracing = ["console-subscriber"]

[[example]]
name = "mania_multi_login"
path = "multi_login.rs"
