[package]
name = "mania-macros"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.98", features = ["full"] }
quote = "1.0.38"
proc-macro2 = "1.0.93"
hex.workspace = true
md-5.workspace = true
