#!/usr/bin/env sh
set -o errexit
set -o nounset

BLUE="\033[0;34m"
RED="\033[0;31m"
NC="\033[0m"
log() {
    printf "%b==>%b %s\n" "$1" "$2" "$3"
}
raise_error() {
    log "$RED" "$NC" "$1" 1>&2
    exit 1
}
info() {
    log "$BLUE" "$NC" "$1"
}

info "Running typos..."
typos -c typos.toml || raise_error "Typos check failed!"

info "Checking code formatting..."
cargo fmt --check || raise_error "Code formatting issues found. Please run 'cargo fmt' to format your code."

info "Building project..."
cargo build --locked || raise_error "Build failed!"

info "Running cargo clippy..."
cargo clippy --locked --all-targets -- --deny warnings || raise_error "Clippy check failed!"

info "Building documentation..."
cargo doc --no-deps --locked || raise_error "Documentation build failed!"

info "Running tests..."
cargo test --locked || raise_error "Tests failed!"

info "Pre-push checks passed!"
