name: Check
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  actions: write

jobs:
  build-nix-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v27

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 107374182
          purge: true
          purge-prefixes: cache-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never

      - name: Build package
        run: |-
          nix build .#

      - name: Save Nix Cache
        if: always()
        uses: nix-community/cache-nix-action/save@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix') }}
