name: Run Checks

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  actions: write

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build-nixpkg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v27

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 107374182
          purge: true
          purge-prefixes: cache-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never

      - name: Build package
        run: |-
          nix build .#

      - name: Save Nix Cache
        if: always()
        uses: nix-community/cache-nix-action/save@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix') }}

  check-clippy:
    runs-on: ubuntu-latest
    needs: build-nixpkg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v27

      - name: Restore Nix Cache
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix') }}

      - name: Check clippy
        run: |
          nix build .#checks.x86_64-linux.clippy 2>&1

  check-fmt:
    runs-on: ubuntu-latest
    needs: build-nixpkg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v27

      - name: Restore Nix Cache
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix') }}

      - name: Check fmt
        run: |
          nix build .#checks.x86_64-linux.fmt 2>&1

  check-doc:
    runs-on: ubuntu-latest
    needs: build-nixpkg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v27

      - name: Restore Nix Cache
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix') }}

      - name: Check doc
        run: |
          nix build .#checks.x86_64-linux.doc 2>&1

  check-test:
    runs-on: ubuntu-latest
    needs: build-nixpkg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v27

      - name: Restore Nix Cache
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix') }}

      - name: Check test
        run: |
          nix build .#checks.x86_64-linux.test 2>&1

  check-audit:
    runs-on: ubuntu-latest
    needs: build-nixpkg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v27

      - name: Restore Nix Cache
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix') }}

      - name: Check test
        run: |
          nix build .#checks.x86_64-linux.audit 2>&1
  check-typo:
    runs-on: ubuntu-latest
    needs: build-nixpkg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v27

      - name: Restore Nix Cache
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix') }}

      - name: Check typo
        run: |
          nix build .#checks.x86_64-linux.typo 2>&1
