name: Automatically Update Flake
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v4
        with:
          ref: "lagrange"
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake inputs"
          pr-labels: |
            dependencies
            automated
